/**:
  ros__parameters:
    input_topic: /sensors/robosense/front/points

    aligned_topic: /sensors/robosense/front/aligned_points
    ground_topic: /sensors/robosense/front/ground_points
    nonground_topic: /sensors/robosense/front/nonground_points
    crop_topic: /sensors/robosense/front/crop_points
    obstacle_topic: /sensors/robosense/front/obstacle_points
    aligned2d_topic: /sensors/robosense/front/aligned_points_2d
    ground2d_topic: /sensors/robosense/front/ground_points_2d
    nonground2d_topic: /sensors/robosense/front/nonground_points_2d
    crop2d_topic: /sensors/robosense/front/crop_points_2d
    obstacle2d_topic: /sensors/robosense/front/obstacle_points_2d

    parent_frame: base_link
    sensor_frame: robosense_front_link
