pointcloud_to_laserscan:
  ros__parameters:
    test_param: true # unused
    target_frame: base_footprint
    transform_tolerance: 0.01
    min_height: 0.05
    max_height: 0.5
    angle_min: -1.5708  # -M_PI/2
    angle_max: 1.5708  # M_PI/2
    angle_increment: 0.0043633  # M_PI/720 for better resolution
    scan_time: 0.3333
    range_min: 0.05
    range_max: 30.0
    use_inf: true
    inf_epsilon: 1.0
    k: 25  # unused
    mean_delta: 5
    mean_N_threshold: 500
    xyz_min_dist: 0.1
    xyz_min: -2.0
    xyz_max: 2.0
    window_x_min: 0.0
    window_x_max: 2.0
    window_y_min: -1.5
    window_y_max: 1.5
    angle_bin_width: 2.0  # in grad
    angle_jump_multiplier: 2.0  # mean_N < angle_jump_multiplier * max
    xyz_bin_width: 0.01
    initial_beta: 0.0  # in grad
    initial_gamma: 0.0  # in grad
