/detector_node:
  ros__parameters:
    model_type: "yolo"
    model_path: "/models/yolo26n_jutestripe_yellowpaper-seg.pt"
    classes: []

    confidence: 0.45
    max_detections: 40

    use_decimation: false
    use_spatial: true
    use_temporal: true
    use_hole_filling: false
    use_mask_filter: true

    use_realsense_ros_wrapper: false
    rgbd_topics: ["/sensors/realsense_rear/rgbd"]
    rgbd_topic: "/sensors/realsense_rear/rgbd"
    color_resolution_width: 640
    color_resolution_height: 480
    fps: 30
    depth_scale_override: 0.0

    publish_annotated_image: false
    annotated_image_topic: "/detector/annotated_image"
    results_topic: "/detector/results"
    status_topic: "/detector/status"

/sensors/realsense_front:
  ros__parameters:
    enable_color: true
    enable_depth: true
    enable_infra: false
    enable_infra1: false
    enable_infra2: false

    enable_rgbd: true
    enable_sync: true

    align_depth.enable: true

    rgb_camera.color_profile: "640x480x30"
    rgb_camera.color_format: "RGB8"

    depth_module.depth_profile: "640x480x30"
    depth_module.depth_format: "Z16"

    pointcloud.enable: false

    publish_tf: false
    tf_publish_rate: 0.0

    initial_reset: true
    reconnect_timeout: 6.0

    diagnostics_period: 1.0

    spatial_filter.enable: true
    temporal_filter.enable: true
    hole_filling_filter.enable: false
    decimation_filter.enable: false
